server:
  servlet:
    context-path: /mall-product
  port: 8084
spring:
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.128.243:80
        username: nacos
        password: nacos
        namespace: 27c4c3f9-2898-497b-9f08-505b39f72513
        ephemeral: false