server:
  port: 8080
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.128.243:80/
        username: nacos
        password: nacos
        namespace: 09acff21-7acc-4180-8511-d2f47d3812b1
        ephemeral: false
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
      #关闭context收敛，才能在service中设置链路限流
      web-context-unify: false
  ############################################################
  #
  # 配置数据源信息
  #
  ############################################################
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP
    #driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动
    url: jdbc:mysql://192.168.128.243:3306/foodie_shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: c1L2~k3J4
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true # 自动提交
      idle-timeout: 600000 # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP # 连接池名字
      max-lifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      connection-test-query: SELECT 1
############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.llmcu.pojo # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml # mapper映射文件
logging:
  level:
    com.llmcu.springcloudalibaba.order.feign: debug
feign:
  client:
    config:
      stock-service:
        #为服务指定日志样式
        loggerLevel: FULL
      product-service:
        # 支持feign原生注解
#        contract: feign.Contract.Default
        #连接超时时间，默认2s
        connectionTimeout: 5000
        #读取超时时间，默认5s，实测感觉是2s
        readTimeout: 5000
        # 拦截器
#        requestInterceptors[0]: com.llmcu.springcloudalibaba.order.feign.intercepter.MyIntercepter
current:
  nacos:
    config:
      namespace: 09acff21-7acc-4180-8511-d2f47d3812b1
