server:
  port: 8080

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public
        ephemeral: false
#被调用服务名
stock-service:
  ribbon:
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule
    NFLoadBalancerRuleClassName: com.llmcu.springcloudalibaba.order.ribbon.MyRoundingRule
ribbon:
  eager-load:
    enabled: true
    clients: order-service
