server:
  port: 8080

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.128.243:80/
        username: nacos
        password: nacos
        namespace: public
        ephemeral: false