server:
  port: 8088

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public
        ephemeral: false
    # 网关配置
    gateway:
      # 路由配置
      routes:
        - id: stock_route
          uri: lb://stock-service
          predicates:
            - Path=/stock-serv/**
              # 匹配到地址类似http://localhost:8088/stock-serv/stock/reduce这样的请求，转发到上方配置的路由uri(http://localhost:8080)
          filters:
            - StripPrefix=1      # 转发前去掉第一层地址http://localhost:8088/stock-serv/stock/add变为http://localhost:8088/stock/add
#被调用服务名
stock-service:
  ribbon:
    #    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule
    NFLoadBalancerRuleClassName: com.llmcu.springcloudalibaba.gateway.ribbon.MyRoundingRule